export interface LeaderboardEntry {
  id?: string
  rank: number
  name: string
  avatar?: string
  college: string
  tasksCompleted: number
  earnings: number
  level: string
  badge: string
  isCurrentUser?: boolean
  streak?: number
}

export const weeklyLeaderboard: LeaderboardEntry[] = [
  {
    id: "1",
    rank: 1,
    name: "Priya Patel",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Bombay",
    tasksCompleted: 28,
    earnings: 12500,
    level: "Expert",
    badge: "🏆",
    streak: 14,
  },
  {
    id: "2",
    rank: 2,
    name: "Arjun Singh",
    avatar: "/diverse-student-portraits.png",
    college: "NIT Trichy",
    tasksCompleted: 25,
    earnings: 11200,
    level: "Expert",
    badge: "🏆",
    streak: 12,
  },
  {
    id: "3",
    rank: 3,
    name: "Sneha Reddy",
    avatar: "/diverse-student-portraits.png",
    college: "BITS Pilani",
    tasksCompleted: 23,
    earnings: 10800,
    level: "Achiever",
    badge: "⭐",
    streak: 9,
  },
  {
    id: "4",
    rank: 4,
    name: "Rahul Sharma",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Delhi",
    tasksCompleted: 21,
    earnings: 9500,
    level: "Achiever",
    badge: "⭐",
    isCurrentUser: true,
    streak: 7,
  },
  {
    id: "5",
    rank: 5,
    name: "Ananya Gupta",
    avatar: "/diverse-student-portraits.png",
    college: "DTU Delhi",
    tasksCompleted: 19,
    earnings: 8900,
    level: "Achiever",
    badge: "⭐",
    streak: 5,
  },
  {
    id: "6",
    rank: 6,
    name: "Vikram Mehta",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Madras",
    tasksCompleted: 18,
    earnings: 8200,
    level: "Explorer",
    badge: "🔍",
    streak: 4,
  },
  {
    id: "7",
    rank: 7,
    name: "Kavya Nair",
    avatar: "/diverse-student-portraits.png",
    college: "NIT Calicut",
    tasksCompleted: 16,
    earnings: 7400,
    level: "Explorer",
    badge: "🔍",
    streak: 3,
  },
  {
    id: "8",
    rank: 8,
    name: "Rohan Das",
    avatar: "/diverse-student-portraits.png",
    college: "IIIT Hyderabad",
    tasksCompleted: 15,
    earnings: 6800,
    level: "Explorer",
    badge: "🔍",
    streak: 2,
  },
  {
    id: "9",
    rank: 9,
    name: "Meera Iyer",
    avatar: "/diverse-student-portraits.png",
    college: "VIT Vellore",
    tasksCompleted: 14,
    earnings: 6100,
    level: "Explorer",
    badge: "🔍",
    streak: 2,
  },
  {
    id: "10",
    rank: 10,
    name: "Aditya Kumar",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Kanpur",
    tasksCompleted: 13,
    earnings: 5500,
    level: "Explorer",
    badge: "🔍",
    streak: 1,
  },
]

export const allTimeLeaderboard: LeaderboardEntry[] = [
  {
    id: "1",
    rank: 1,
    name: "Karthik Subramanian",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Madras",
    tasksCompleted: 312,
    earnings: 52000,
    level: "Legend",
    badge: "👑",
    streak: 45,
  },
  {
    id: "2",
    rank: 2,
    name: "Divya Krishnan",
    avatar: "/diverse-student-portraits.png",
    college: "IISc Bangalore",
    tasksCompleted: 287,
    earnings: 48500,
    level: "Legend",
    badge: "👑",
    streak: 38,
  },
  {
    id: "3",
    rank: 3,
    name: "Amit Verma",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Kharagpur",
    tasksCompleted: 245,
    earnings: 41200,
    level: "Legend",
    badge: "👑",
    streak: 30,
  },
  {
    id: "4",
    rank: 4,
    name: "Neha Sharma",
    avatar: "/diverse-student-portraits.png",
    college: "NIT Surathkal",
    tasksCompleted: 198,
    earnings: 33500,
    level: "Master",
    badge: "💎",
    streak: 22,
  },
  {
    id: "5",
    rank: 5,
    name: "Rajesh Kumar",
    avatar: "/diverse-student-portraits.png",
    college: "BITS Goa",
    tasksCompleted: 176,
    earnings: 29800,
    level: "Master",
    badge: "💎",
    streak: 18,
  },
  {
    id: "18",
    rank: 18,
    name: "Rahul Sharma",
    avatar: "/diverse-student-portraits.png",
    college: "IIT Delhi",
    tasksCompleted: 47,
    earnings: 8500,
    level: "Achiever",
    badge: "⭐",
    isCurrentUser: true,
    streak: 7,
  },
]

export const leaderboardData = {
  weekly: weeklyLeaderboard,
  allTime: allTimeLeaderboard,
}
